dist: trusty
sudo: false
language: python
python:
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
addons:
  apt:
    packages:
    - libydpdict2
cache: pip
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.3 ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.3 ]]; then if_pylint=:; fi
install:
- pip install lxml
- pip install pydiatra $pyflakes
- $if_pylint pip install pylint
- pip install docutils
- pip install pygments
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- python3 -m pydiatra .
- python3 -m pyflakes .
- $if_pylint private/run-pylint
- private/check-rst
- make -C doc
- make install PREFIX=~/.local
- cd /
- ydpy --help
- export MANPATH=~/.local/share/man MANWIDTH=80
- man 1 ydpy | grep -A 10 -w YDPY

# vim:ts=2 sts=2 sw=2 et
