dist: trusty
language: python
matrix:
  include:
  - python: "3.3"
    env: LXML=3.0
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7-dev"
addons:
  apt:
    packages:
    - libydpdict2
cache: pip
before_install:
- lxml="lxml${LXML:+==$LXML}"
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.3 ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.3 ]]; then if_pylint=:; fi
install:
- python3 -m pip install $lxml
- python3 -m pip install pydiatra $pyflakes
- $if_pylint python3 -m pip install pylint
- python3 -m pip install docutils
- python3 -m pip install pygments
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- python3 -m pydiatra .
- python3 -m pyflakes .
- $if_pylint private/run-pylint
- private/check-rst
- make -C doc
- make install PREFIX=~/.local
- cd /
- ydpy --help
- ydpy --version
- ydpy --path "$TRAVIS_BUILD_DIR/test"
- export MANPATH=~/.local/share/man MANWIDTH=80
- man 1 ydpy | grep -A 10 -w YDPY

# vim:ts=2 sts=2 sw=2 et
